### ISSUE TITLE
Implement .bow format conversion 0.5 -> 0.6

### ISSUE THREAD

**Issue by stfnp** [bow-simulation/virtualbow#121]
In GitLab by **spfeifer** on Dec 19, 2018, 00:58

**Comment by lleroy** [comment]
Would it not be easier to try to make the ".bow" format backward compatible by default?

I mean, instead of using the "at(key)", use the "value(key, default_value)"?
for example:

static void from_json(const json& obj, Dimensions& value)
{
    ...
    value.handle_angle = obj.at("handle_angle");
    value.crown_curvature = obj.value("crown_curvature", 0.0);
}

**Comment by stfnp** [comment]
If I understand you correctly, this would use default values for keys that are no longer there in newer versions of the format, right? The problem with this would be that it changes the bow model without the users noticing.

The current solution is in the file [Compatibility.hpp](https://github.com/bow-simulation/virtualbow/blob/develop/source/bow/input/Compatibility.hpp). Each new version of the program adds a "conversion function" that takes the previous format and converts it to the next version, depending on what has changed. So users can load any older file and all the data is converted to the latest version through a chain of conversions.

**Comment by lleroy** [comment]
no, my proposal would be to add defaults for parameters that did not exist in the previous version, so you can load old files with a newer version.

**Comment by stfnp** [comment]
Oh, now I see what you mean. That definitely makes sense then.
