### ISSUE TITLE
VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by sbrcher** [bow-simulation/virtualbow#155]
I just installed version 0.6.1 x64 on Windows 10 and got the attached error message when running the program.

![Capture](https://user-images.githubusercontent.com/16884393/69009023-d541a100-0916-11ea-8c47-c7ce639875ec.PNG)

**Comment by stfnp** [comment]
Thank you for reporting this. You could try the following things:
* Make sure all Windows updates are installed, especially if your system is a fresh install
* Try installing the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) in case it isn't already installed.

Let me know if any of that helped.

**Comment by sbrcher** [comment]
Thanks.  I installed vc_redist.x64.exe per your link and now it works.  Does the installer currently check for this being installed?

**Comment by stfnp** [comment]
The installer previously did that. But I somehow got the impression that this C++ runtime stuff is now part of Windows and doesn't have to be installed separately anymore ([Universal C Runtime](https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/)). Seems like I was wrong, even though it seemed to work on my machine.

**Comment by stfnp** [comment]
The next version of VirtualBow is built with MinGW instead of Microsoft's Visual C++ compiler. So we don't need the Microsoft C++ runtime anymore, which also solves this issue.
