### ISSUE TITLE
Don't show application name behind every window title

### ISSUE THREAD

**Issue by stfnp** [bow-simulation/virtualbow#2]
In GitLab by **spfeifer** on Apr 6, 2017, 20:31

When setting the application name via

        QGuiApplication::setApplicationDisplayName("Bow Simulator");

a dash followed by the application name is displayed behind every window. This is however only wanted for the main window and not for the various small dialogues.

**Comment by lleroy** [comment]
this is a workaround - albeit a bit of a hack.


diff --git a/source/gui/Application.cpp b/source/gui/Application.cpp
index 1a5174f..6cf2dfc 100644
--- a/source/gui/Application.cpp
+++ b/source/gui/Application.cpp
@@ -21,7 +21,7 @@ int Application::run(int argc, char* argv[])
 {
     QApplication app(argc, argv);
     app.setApplicationName(Config::APPLICATION_NAME);
-    app.setApplicationDisplayName(Config::APPLICATION_DISPLAY_NAME);
+    app.setApplicationDisplayName(QString::null);
     app.setApplicationVersion(Config::APPLICATION_VERSION);
     app.setOrganizationDomain(Config::APPLICATION_WEBSITE);

diff --git a/source/gui/MainWindow.cpp b/source/gui/MainWindow.cpp
index e607d96..28ff253 100755
--- a/source/gui/MainWindow.cpp
+++ b/source/gui/MainWindow.cpp
@@ -95,7 +95,7 @@ MainWindow::MainWindow()
     // Set Window's modification indicator when data has changed
     QObject::connect(editor, &BowEditor::modified, [&]{
         InputData new_data = editor->getData();
-        this->setWindowModified(new_data != data);
+        this->setModified(new_data != data);
     });

     // Set initial input data
@@ -117,7 +117,7 @@ bool MainWindow::loadFile(const QString& path)
         data.load(path.toStdString());
         editor->setData(data);
         setCurrentFile(path);
-        setWindowModified(false);
+        setModified(false);
         return true;
     }
     catch(const std::exception& e)  // Todo
@@ -134,7 +134,7 @@ bool MainWindow::saveFile(const QString& path)
         data = editor->getData();
         data.save(path.toStdString());
         setCurrentFile(path);
-        setWindowModified(false);
+        setModified(false);

         return true;
     }
@@ -168,7 +168,7 @@ void MainWindow::newFile()
     editor->setData(data);

     setCurrentFile(QString());
-    setWindowModified(false);
+    setModified(false);
 }

 void MainWindow::open()
@@ -286,10 +286,19 @@ void MainWindow::about()
     );
 }

+void MainWindow::setModified(bool modified)
+{
+    QApplication::setApplicationDisplayName(Config::APPLICATION_DISPLAY_NAME);
+    setWindowModified(modified);
+    QTimer::singleShot(0, [](){QApplication::setApplicationDisplayName(QString::null);});
+}
+
 void MainWindow::setCurrentFile(const QString &path)
 {
     current_file = path;
+    QApplication::setApplicationDisplayName(Config::APPLICATION_DISPLAY_NAME);
     setWindowFilePath(current_file.isEmpty() ? "untitled.bow" : current_file);
+    QTimer::singleShot(0, [](){QApplication::setApplicationDisplayName(QString::null);});
 }

 bool MainWindow::optionalSave()    // true: Discard and save, false: Cancel and don't save
diff --git a/source/gui/MainWindow.hpp b/source/gui/MainWindow.hpp
index 94ba295..62ed292 100755
--- a/source/gui/MainWindow.hpp
+++ b/source/gui/MainWindow.hpp
@@ -32,5 +32,6 @@ private:
     void about();

     void setCurrentFile(const QString& path);
+    void setModified(bool modified);
     bool optionalSave();
 };

**Comment by stfnp** [comment]
Cool, thanks for working on that! If a hack is what it takes to get the desired user experience... so be it. I'll try it out and merge your pull request as soon as I get around to it.

In the meantime... could you help me understand how it works? Seems like the magic happens in this line:

    QTimer::singleShot(0, [](){QApplication::setApplicationDisplayName(QString::null);});

It's a timer that just fires immediately, right? Why is it different from just calling `QApplication::setApplicationDisplayName(QString::null)` directly?

**Comment by lleroy** [comment]
shot story : if you call it directly, it doesn't work :-)
long story:
setWindowFilePath() sets the path, and some "something changed" event is put on the event queue. by using the singleshot with 0 delay, the execution of the lambda is also posted on the event queue, and executed after the notification is handled to update the window title in a callback. if you call the function directly, it's executed before the event is handled off the event queue
