### ISSUE TITLE
String length in results wrong units

### ISSUE THREAD

**Issue by FunktasticShawn** [bow-simulation/virtualbow#236]
String length show a mass unit.  When it is mass is set to grams the number displayed is the length in mm.  But I haven't found any other setting that shows a sensible result.  I have seen the issue in both Windows (10) and in Linux Mint (most recent LTS).
![results](https://user-images.githubusercontent.com/33184629/188050187-9f7a8bea-b35a-44a6-a727-41f3b7c578e8.png)

**Comment by stfnp** [comment]
Thanks for reporting! Looks like a copy/paste error in this line:

https://github.com/bow-simulation/virtualbow/blob/9e8c960856e2531a892ea1a9a4899902a9a82eef/source/post/OutputWidget.cpp#L91

**Comment by stfnp** [comment]
Thanks for reporting! Looks like a copy/paste error in this line:

https://github.com/bow-simulation/virtualbow/blob/9e8c960856e2531a892ea1a9a4899902a9a82eef/source/post/OutputWidget.cpp#L91
